definitions:
  # Reusable definitions go in this section
  scripts:
    - &shorebird_install
      name: Install Shorebird CLI
      script: |
        # Install the Shorebird CLI
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
        # Set Shorebird PATH
        echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV        
    - &flutter_analyze
      name: Run static code analysis
      script: flutter analyze
    - &setup_local_properties
      name: Set up local.properties
      script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties" 
    
workflows:
  # Define your workflows here
  release-android-workflow:
    name: Release Android Workflow
    environment:
      android_signing:
        - todoy_pomodoro_app_key
      groups:
        - todo_y_pomodoro_app
        - google_credentials
      vars:
        PACKAGE_NAME: "com.solucionesdigitalesapp.todoandpomodoro" 
        GOOGLE_PLAY_TRACK: "production"
      flutter: 3.19.2
      xcode: 14.3.1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
    scripts:
      - *setup_local_properties
      - *shorebird_install   
      - name: Build with Shorebird
        script: |
        BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          export SHOREBIRD_TOKEN="$SHOREBIRD_TOKEN" && shorebird release android --flavor production -t lib/main_production.dart --force -- \
          --build-name=1.0.0 \
          --build-number=$BUILD_NUMBER          
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false

  patch-android-workflow:
    name: Patch Android Workflow
    environment:
      android_signing:
        - codemagic
      groups:
        - todo_y_pomodoro_app
      flutter: 3.19.2
      xcode: 14.3.1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
    scripts:
      - *setup_local_properties
      - *shorebird_install 
      - name: Patch Android app with Shorebird
        script: export SHOREBIRD_TOKEN="$SHOREBIRD_TOKEN" && shorebird patch android --force --flavor production -t lib/main_production.dart
    artifacts:
      - build/**/outputs/**/*.aab