name: todo_y_pomodoro_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sentry_flutter: ^7.18.0
  flutter_svg: ^1.0.3
  package_info: ^2.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  cloud_firestore: ^4.8.1
  duration_picker: ^1.1.1
  circular_countdown_timer: ^0.2.3
  flutter_i18n: ^0.33.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.6
  google_mobile_ads: ^4.0.0
  collection: ^1.17.0
  shorebird_code_push: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  # android: false
  ios: false
  image_path: "assets/images/launcher_icon.png"
  remove_alpha_ios: true

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/i18n/
    - shorebird.yaml

  fonts:
    - family: SourceSans3
      fonts:
        - asset: assets/fonts/SourceSans3-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSans3-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSans3-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSans3-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceSans3-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSans3-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSans3-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SourceSans3-Black.ttf
          weight: 900

